runtime: nodejs14

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "keys/digitallibrary-343516.json"
  INSTANCE_CONNECTION_NAME: "digitallibrary-343516:us-central1:digital-library"
  DB_USER: "digital-library"
  DB_PASS: 'sahar1234'
  DB_NAME: "library"
  MJ_APIKEY_PUBLIC: "c23a05e9932f9034542d58093f3253d0"
  MJ_APIKEY_PRIVATE: "f51b8b7abdd2dfd183a151ac9392f046"